import React, { useState, useEffect } from 'react';
import { useNavigate } from 'react-router-dom';
import Header from '../components/Header';
import { staffAPI, driverAPI } from '../services/api';
import './AdminDashboard.css';

const AdminDashboard = () => {
  const navigate = useNavigate();
  const [formData, setFormData] = useState({
    firstNameStaff: '',
    lastNameStaff: '',
    emailStaff: '',
    firstNameDriver: '',
    lastNameDriver: '',
    firstNameFire: '',
    lastNameFire: '',
    firstNameDriverFire: '',
    lastNameDriverFire: '',
    rewardFirstName: '',
    rewardLastName: ''
  });

  const [errorMessage, setErrorMessage] = useState('');
  const [successMessage, setSuccessMessage] = useState('');
  const [staffDisplayName, setStaffDisplayName] = useState('');
  const [staffList, setStaffList] = useState([]);
  const [driverList, setDriverList] = useState([]);

  // Load staff and drivers from backend on mount
  useEffect(() => {
    loadStaff();
    loadDrivers();
  }, []);

  const loadStaff = async () => {
    try {
      const response = await staffAPI.getAll();
      const backendStaff = response.data;
      const formattedStaff = backendStaff.map(staff => ({
        id: staff.staffId,
        firstName: staff.firstName,
        lastName: staff.lastName,
        status: staff.status,
        username: staff.username,
        hiredDate: staff.hiredDate
      }));
      setStaffList(formattedStaff);
    } catch (error) {
      console.error('Error loading staff:', error);
      // Fallback to localStorage
      const savedStaff = localStorage.getItem('staffList');
      if (savedStaff) {
        setStaffList(JSON.parse(savedStaff));
      }
    }
  };

  const loadDrivers = async () => {
    try {
      const response = await driverAPI.getAll();
      const backendDrivers = response.data;
      const formattedDrivers = backendDrivers.map(driver => ({
        id: driver.driverId,
        firstName: driver.firstName,
        lastName: driver.lastName,
        username: driver.username,
        status: driver.status || 'Active',
        hiredDate: driver.hiredDate
      }));
      setDriverList(formattedDrivers);
    } catch (error) {
      console.error('Error loading drivers:', error);
      // Fallback to localStorage
      const savedDrivers = localStorage.getItem('driverList');
      if (savedDrivers) {
        setDriverList(JSON.parse(savedDrivers));
      }
    }
  };

  const handleChange = (e) => {
    setFormData({
      ...formData,
      [e.target.name]: e.target.value
    });
  };

  const isValidUsername = (name) => {
    const usernamePattern = /^[a-zA-Z]+$/;
    return usernamePattern.test(name);
  };

  const isValidEmail = (email) => {
    const emailPattern = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;
    return emailPattern.test(email);
  };

  const handleStaffHire = (e) => {
    e.preventDefault();
    setErrorMessage('');
    setSuccessMessage('');

    if (!formData.firstNameStaff || !formData.lastNameStaff || !formData.emailStaff) {
      setErrorMessage('Staff Name please fill in all fields.');
      return;
    }

    if (!isValidUsername(formData.firstNameStaff)) {
      setErrorMessage('First name contains invalid characters. Only letters are allowed.');
      return;
    }

    if (!isValidUsername(formData.lastNameStaff)) {
      setErrorMessage('Last name contains invalid characters. Only letters are allowed.');
      return;
    }

    if (!isValidEmail(formData.emailStaff)) {
      setErrorMessage('Please enter a valid email address.');
      return;
    }

    // Check if staff already exists
    const staffExists = staffList.some(
      staff => staff.firstName === formData.firstNameStaff && staff.lastName === formData.lastNameStaff
    );

    if (staffExists) {
      setErrorMessage('Staff member already exists!');
      return;
    }

    const newStaff = {
      firstName: formData.firstNameStaff,
      lastName: formData.lastNameStaff,
      email: formData.emailStaff,
      status: 'Active',
      hiredDate: new Date().toISOString().split('T')[0]
    };

    // Create staff in backend (LoginCredentials are created automatically)
    staffAPI.create(newStaff)
      .then((response) => {
        // Get the username generated by the backend
        const generatedUsername = response.data.username;

        setStaffDisplayName(generatedUsername);
        setSuccessMessage(`Staff account created successfully! Username: ${generatedUsername}`);
        // Reload staff list
        loadStaff();
        // Clear form
        setFormData({
          ...formData,
          firstNameStaff: '',
          lastNameStaff: '',
          emailStaff: ''
        });
      })
      .catch((error) => {
        console.error('Error creating staff:', error);
        const errorMsg = error.response?.data?.error || 'Failed to create staff member. Please try again.';
        setErrorMessage(errorMsg);
      });
  };

  const handleDriverHire = (e) => {
    e.preventDefault();
    setErrorMessage('');
    setSuccessMessage('');

    if (!formData.firstNameDriver || !formData.lastNameDriver) {
      setErrorMessage('Driver Name please fill in all fields.');
      return;
    }

    if (!isValidUsername(formData.firstNameDriver)) {
      setErrorMessage('First name contains invalid characters. Only letters are allowed.');
      return;
    }

    if (!isValidUsername(formData.lastNameDriver)) {
      setErrorMessage('Last name contains invalid characters. Only letters are allowed.');
      return;
    }

    // Check if driver already exists
    const driverExists = driverList.some(
      driver => driver.firstName === formData.firstNameDriver && driver.lastName === formData.lastNameDriver
    );

    if (driverExists) {
      setErrorMessage('Driver already exists!');
      return;
    }

    const driverUsername = formData.lastNameDriver + '12';
    const newDriver = {
      firstName: formData.firstNameDriver,
      lastName: formData.lastNameDriver,
      username: driverUsername,
      hiredDate: new Date().toISOString().split('T')[0]
    };

    // Create driver in backend
    driverAPI.create(newDriver)
      .then((response) => {
        setSuccessMessage(`Driver ${formData.firstNameDriver} ${formData.lastNameDriver} hired successfully!`);
        // Reload driver list
        loadDrivers();
        // Clear form
        setFormData({
          ...formData,
          firstNameDriver: '',
          lastNameDriver: ''
        });
      })
      .catch((error) => {
        console.error('Error creating driver:', error);
        const errorMsg = error.response?.data?.error || 'Failed to create driver. Please try again.';
        setErrorMessage(errorMsg);
      });
  };

  const handleStaffFireById = async (id, firstName, lastName) => {
    try {
      await staffAPI.update(id, { status: 'Inactive' });
      setSuccessMessage(`Staff ${firstName} ${lastName} set to Inactive!`);
      loadStaff();
    } catch (error) {
      console.error('Error updating staff status:', error);
      setErrorMessage('Failed to update staff status. Please try again.');
    }
  };

  const handleStaffReactivate = async (id, firstName, lastName) => {
    try {
      await staffAPI.update(id, { status: 'Active' });
      setSuccessMessage(`Staff ${firstName} ${lastName} reactivated successfully!`);
      loadStaff();
    } catch (error) {
      console.error('Error reactivating staff:', error);
      setErrorMessage('Failed to reactivate staff. Please try again.');
    }
  };

  const handleDriverDeactivate = async (id, firstName, lastName) => {
    try {
      await driverAPI.update(id, { status: 'Inactive' });
      setSuccessMessage(`Driver ${firstName} ${lastName} set to Inactive!`);
      loadDrivers();
    } catch (error) {
      console.error('Error updating driver status:', error);
      setErrorMessage('Failed to update driver status. Please try again.');
    }
  };

  const handleDriverReactivate = async (id, firstName, lastName) => {
    try {
      await driverAPI.update(id, { status: 'Active' });
      setSuccessMessage(`Driver ${firstName} ${lastName} reactivated successfully!`);
      loadDrivers();
    } catch (error) {
      console.error('Error reactivating driver:', error);
      setErrorMessage('Failed to reactivate driver. Please try again.');
    }
  };

  const handleDriverFireById = async (id, firstName, lastName) => {
    try {
      await driverAPI.delete(id);
      setSuccessMessage(`Driver ${firstName} ${lastName} deleted successfully!`);
      loadDrivers();
    } catch (error) {
      console.error('Error deleting driver:', error);
      setErrorMessage('Failed to delete driver. Please try again.');
    }
  };

  const handleLogout = () => {
    navigate('/login');
  };

  const handleRewards = () => {
    navigate('/rewards');
  };

  return (
    <div className="container">
      <Header showLogin={false} />
      <main className="admin-staff-content">
        <section className="staff-sections">
          <div className="staff-hire">
            <h2 className="hire-staff-title">Add New Staff</h2>

            {errorMessage && (
              <div className="error-message" style={{ display: 'block' }}>
                {errorMessage}
              </div>
            )}
            {successMessage && (
              <div className="success-message" style={{ display: 'block' }}>
                {successMessage}
              </div>
            )}

            <form onSubmit={handleStaffHire}>
              <div className="form-group">
                <label htmlFor="firstNameStaff">First Name</label>
                <input
                  type="text"
                  id="firstNameStaff"
                  name="firstNameStaff"
                  value={formData.firstNameStaff}
                  onChange={handleChange}
                />
              </div>
              <div className="form-group">
                <label htmlFor="lastNameStaff">Last Name</label>
                <input
                  type="text"
                  id="lastNameStaff"
                  name="lastNameStaff"
                  value={formData.lastNameStaff}
                  onChange={handleChange}
                />
              </div>
              <div className="form-group">
                <label htmlFor="emailStaff">Email Address</label>
                <input
                  type="email"
                  id="emailStaff"
                  name="emailStaff"
                  value={formData.emailStaff}
                  onChange={handleChange}
                />
              </div>
              <button type="submit" className="hire-staff-btn">
                Create Staff Account
              </button>
            </form>

            {staffDisplayName && (
              <div id="display-staff">
                <p>
                  Staff Username: <span id="staffDisplayName">{staffDisplayName}</span>
                </p>
              </div>
            )}

            {staffList.length > 0 && (
              <>
                {staffList.filter(staff => staff.status === 'Active').length > 0 && (
                  <div className="employee-list">
                    <h3>Active Staff</h3>
                    <ul>
                      {staffList.filter(staff => staff.status === 'Active').map(staff => (
                        <li key={staff.id}>
                          <div className="employee-info">
                            <span>{staff.firstName} {staff.lastName} - Username: {staff.username} - Hired: {staff.hiredDate}</span>
                            <button
                              className="fire-btn-inline"
                              onClick={() => handleStaffFireById(staff.id, staff.firstName, staff.lastName)}
                            >
                              Deactivate
                            </button>
                          </div>
                        </li>
                      ))}
                    </ul>
                  </div>
                )}
                {staffList.filter(staff => staff.status === 'Inactive').length > 0 && (
                  <div className="employee-list">
                    <h3>Inactive Staff</h3>
                    <ul>
                      {staffList.filter(staff => staff.status === 'Inactive').map(staff => (
                        <li key={staff.id}>
                          <div className="employee-info">
                            <span>{staff.firstName} {staff.lastName} - Username: {staff.username} - Hired: {staff.hiredDate}</span>
                            <button
                              className="fire-btn-inline"
                              onClick={() => handleStaffReactivate(staff.id, staff.firstName, staff.lastName)}
                            >
                              Reactivate
                            </button>
                          </div>
                        </li>
                      ))}
                    </ul>
                  </div>
                )}
              </>
            )}
          </div>

          <div className="hire-driver">
            <h2 className="hire-driver-title">Hire Driver</h2>
            <form onSubmit={handleDriverHire}>
              <div className="form-group">
                <label htmlFor="firstNameDriver">First Name</label>
                <input
                  type="text"
                  id="firstNameDriver"
                  name="firstNameDriver"
                  value={formData.firstNameDriver}
                  onChange={handleChange}
                />
              </div>
              <div className="form-group">
                <label htmlFor="lastNameDriver">Last Name</label>
                <input
                  type="text"
                  id="lastNameDriver"
                  name="lastNameDriver"
                  value={formData.lastNameDriver}
                  onChange={handleChange}
                />
              </div>
              <button className="hire-driver-btn" type="submit">
                Hire Driver
              </button>
            </form>

            {driverList.length > 0 && (
              <>
                {driverList.filter(driver => driver.status === 'Active').length > 0 && (
                  <div className="employee-list">
                    <h3>Active Drivers</h3>
                    <ul>
                      {driverList.filter(driver => driver.status === 'Active').map(driver => (
                        <li key={driver.id}>
                          <div className="employee-info">
                            <span>{driver.firstName} {driver.lastName} - Hired: {driver.hiredDate}</span>
                            <button
                              className="fire-btn-inline"
                              onClick={() => handleDriverDeactivate(driver.id, driver.firstName, driver.lastName)}
                            >
                              Deactivate
                            </button>
                          </div>
                        </li>
                      ))}
                    </ul>
                  </div>
                )}
                {driverList.filter(driver => driver.status === 'Inactive').length > 0 && (
                  <div className="employee-list">
                    <h3>Inactive Drivers</h3>
                    <ul>
                      {driverList.filter(driver => driver.status === 'Inactive').map(driver => (
                        <li key={driver.id}>
                          <div className="employee-info">
                            <span>{driver.firstName} {driver.lastName} - Hired: {driver.hiredDate}</span>
                            <button
                              className="fire-btn-inline"
                              onClick={() => handleDriverReactivate(driver.id, driver.firstName, driver.lastName)}
                            >
                              Reactivate
                            </button>
                          </div>
                        </li>
                      ))}
                    </ul>
                  </div>
                )}
              </>
            )}
          </div>
        </section>


        <section className="rewards-sections">
          <div className="rewards-approvals">
            <h2 className="reward-approval-title">Rewards Approvals</h2>
            <form>
              <div className="form-group">
                <label htmlFor="rewardFirstName">First Name</label>
                <input
                  type="text"
                  id="rewardFirstName"
                  name="rewardFirstName"
                  value={formData.rewardFirstName}
                  onChange={handleChange}
                  required
                />
              </div>
              <div className="form-group">
                <label htmlFor="rewardLastName">Last Name</label>
                <input
                  type="text"
                  id="rewardLastName"
                  name="rewardLastName"
                  value={formData.rewardLastName}
                  onChange={handleChange}
                  required
                />
              </div>
            </form>
          </div>
        </section>

        <button className="logout-btn" onClick={handleLogout}>
          Logout
        </button>
      </main>
    </div>
  );
};

export default AdminDashboard;
